### ISSUE TITLE
Use msgid as a translation value in po-2-i18next conversion

### ISSUE THREAD

**Issue by obrejla** [locize/gettext-converter#12]
## 🚀 Feature Proposal

Add an option which will allow to fallback `msgid` from `.po` file to act as a translation value in generated i18next `.json` (when provided `msgstr` is empty)

## Motivation

We usually have `.po` files where are just `msgid`s defined (as english sentences) and `msgstr`s are empty, and other tools can handle that they fallback to the msgid as a translation value (not for plurals, theirs `msgstr[]`s are defined explicitly as normal). But now, to be able to generate proper i18next json (v4), we have to have the `msgid` duplicated to `msgstr`.

## Example

I.e. this `.po` file snippet:

```po
msgid "Preview failed"
msgstr ""
```

will generate this i18next json:

```json
{
    "Preview failed: "Preview failed"
}
```

Thanks for the consideration.

**Comment by adrai** [comment]
Is it possible for you to create a PR introducing a new option that would address this?

**Comment by adrai** [comment]
v1.3.0 includes the option `fallbackToMsgId`

```js
    po2i18next(myPoFile, {
      compatibilityJSON: 'v4',
      fallbackToMsgId: true
    })
```

**Comment by obrejla** [comment]
Thanks a lot @adrai !
