### ISSUE TITLE
Plurals generation from .po for language with no plurals

### ISSUE THREAD

**Issue by pierrebaronqumu** [locize/gettext-converter#5]
## 🐛 Bug Report

Hi,

I am using this tool to generate locales in multiple languages. My source files are `.po` files that I transform into `.json` files. Everything works fine for most languages but I noticed that the plural forms are not working correctly if the language does not have any plural forms (like Japanese)

I receive the `.po` files from a translation tool and I, therefore, do not want to transform them.

## To Reproduce

here is my .po file for English
```js
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

msgid "my_string"
msgid_plural "my_string"
msgstr[0] "{{count}} foo"
msgstr[0] "{{count}} bar"

```

here is my .po file for Japanse

```js
"Plural-Forms: nplurals=1; plural=0;\n"

msgid "my_string"
msgid_plural "my_string"
msgstr[0] "{{count}} foo"
```

## Expected behavior

I should expect the following JSON for English -> OK

```js
{
  "my_string": "{{count}} foo"
  "my_string_plural": "{{count}} bar"
}
```

I should expect the following JSON for Japanese

```js
{
  "my_string": "{{count}} foo"
}
```

Here is what I receive for Japanese

```js
{
  "my_string_0": "{{count}} foo"
}
```

While we can argue that Japanese should not use the plural form, I tested several translations platforms and they all return that format so I think we should support it.

**Comment by jamuhl** [comment]
Looking at i18next (v3 plurals) it uses the _0 suffix for "plurals" in those languages: https://jsfiddle.net/6bpxsgd4

**Comment by adrai** [comment]
Yes, _0 seems the correct suffix for ja in v3
v1 and v2 used no suffix for ja

**Comment by pierrebaronqumu** [comment]
I see the following in https://www.i18next.com/misc/json-format#i18next-json-v3

```
"keyPluralSimple": "the singular",
"keyPluralSimple_plural": "the plural",
```

**Comment by adrai** [comment]
> I see the following in https://www.i18next.com/misc/json-format#i18next-json-v3
> 
> ```
> "keyPluralSimple": "the singular",
> "keyPluralSimple_plural": "the plural",
> ```

This is just an example... languages like ja are not reflected there
But here you can check for ja: https://jsfiddle.net/6bpxsgd4


v4:
![image](https://user-images.githubusercontent.com/1086194/153249826-4d55b938-10eb-4679-b287-57975c60e9ff.png)

v3:
![image](https://user-images.githubusercontent.com/1086194/153249882-6986f576-d49e-4ef5-9e77-5bd0252ccf79.png)

v2:
![image](https://user-images.githubusercontent.com/1086194/153249955-e1dabfbd-d354-4794-ab27-19e1abc69d33.png)

v1:
![image](https://user-images.githubusercontent.com/1086194/153250012-8d91a1d4-9d9c-4984-bd2e-e814e297307d.png)

**Comment by pierrebaronqumu** [comment]
> This is just an example... languages like ja are not reflected there

Right, I guess my confusion came from here. Looks like everything is working fine then! 

Thanks for your input!

**Comment by adrai** [comment]
all ok 👍😉
